### ISSUE TITLE
Question: Raspberry Pi 4/5 as server?

### ISSUE THREAD

**Issue by mrstruijk** [radishnet/radishnet-server#12]
Hi Jelle, 

Thanks for your talk the other day at the Surf XR day! 

Question: do you think Pi 4/5 could be enough to run as a server for a small 2-player system? I'm guessing the answer would be 'it depends', but is it in any way, shape, or form reasonable for me to look into this further? 

The reason I want something simple and small is that it needs to be quite portable and replicable. I'd prefer the server to auto-start upon booting, so the system would require minimal support from my side, once it's out in the field.

Thanks, 
Best, 
Maarten

**Comment by JelleWolbers** [comment]
Hi Maarten,

You're welcome for the talk! I'm really sorry about replying so embarrassingly late; I did not see any notification so I completely missed it. I will look into this and fix it.

In RadishNet the server actually handles relatively little data so I don't think running the server on a Raspberry Pi should be a problem! I'll send you my e-mail so I can help you out if you'd like.

Best,
Jelle

**Comment by mrstruijk** [comment]
Not a worry! Github is not too forthcoming with those kinds of notifications. 

I'll contact you when I'm having some time to look into this further.

Thanks Jelle!

Maarten
